server:
  port: 8081
spring:
  cloud:
    config:
      fail-fast: false
      server:
        git:
          default-label: multiple-instances
          uri: https://github.com/sanzlju/projectos_juanjo
          search-paths: config-data
          username: sanzlju
          password: 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
  application:
    name: config-service
