server:
  port: 8081
spring:
  cloud:
    config:
      fail-fast: false
      server:
        git:
          default-label: config-server
          uri: https://github.com/sanzlju/projectos_juanjo
          search-paths: config-data
          username: sanzlju
          password: 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
  application:
    name: config-service
