server:
  port: 8081
spring:
  cloud:
    config:
      fail-fast: false
      server:
        git:
          default-label: multiple-instances
          uri: https://github.com/sanzlju/projectos_juanjo
          search-paths: config-data
          username: sanzlju
          password: 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
  application:
    name: config-service
